import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastsWrapper } from "@/features/toasts/ui/toasts-wrapper";
import LoginChecker from "@/widgets/auth/LoginChecker";
import FullPageLoader from "@/features/fullpage-loader/ui/FullPageLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ToastsWrapper />
        <LoginChecker />
        <FullPageLoader />
      </body>
    </html>
  )
}