version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/codemate
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/vertexai.json
      - VERTEX_PROJECT_ID=focused-world-446007-v1
      - VERTEX_LOCATION=us-central1
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  socket-server:
    build: ./socket-server
    ports:
      - "4001:4001"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge

