version: "3.9"
services:
  mongo:
    image: mongo:8
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: dinni1214/ai-codemate-be
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_APPLICATION_CREDENTIALS=/
      - VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID}
      - VERTEX_LOCATION=${VERTEX_LOCATION}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_INVITE_SECRET=${JWT_INVITE_SECRET}
      - JWT_INVITE_EXPIRES_IN=${JWT_INVITE_EXPIRES_IN}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: dinni1214/ai-codemate-fe
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=${BACKEND_API_URL}
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=${NEXT_PUBLIC_GITHUB_CLIENT_ID}
      - NEXT_PUBLIC_GITHUB_REDIRECT_URI=${NEXT_PUBLIC_GITHUB_REDIRECT_URI}
    depends_on:
      - backend
    networks:
      - app-network

  socket-server:
    build: dinni1214/ai-codemate-socket
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge

