version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ Docker CLI 권한 부여
      - /tmp:/tmp                                    # ✅ 코드 실행 파일 마운트
    environment:
      - MONGO_URI=mongodb://mongo:27017/codemate
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/vertexai.json
      - DOCKER_HOST=unix:///var/run/docker.sock
      - VERTEX_PROJECT_ID=focused-world-446007-v1
      - VERTEX_LOCATION=us-central1
    depends_on:
      - mongo
  
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

  socket-server:
    build: ./socket-server
    ports:
      - "4001:4001"
    volumes:
      - ./socket-server:/app
    depends_on:
      - backend
    command: node index.js

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
