version: "3.9"
services:
  mongo:
    image: mongo:8
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: dinni1214/ai-codemate-be
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: dinni1214/ai-codemate-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  socket-server:
    build: dinni1214/ai-codemate-socket
    ports:
      - "4001:4001"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge

