name: Deploy to GCP

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.GCP_USER }}/app"
      - name: Set GCP credentials env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
      - name: Run docker compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/app
            docker compose down --remove-orphans
            docker compose up -d --build
