name: Deploy to GCP

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
	    # GitHub Actions 러너가 코드 클론
      - name: Checkout code
        uses: actions/checkout@v3
			# Actions가 GCP로 코드 복사 (SCP)
      - name: Copy files to GCP VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.GCP_USER }}/app"
      - name: Set GCP credentials env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV

			# GCP에서 빌드 및 실행
      - name: Run docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/app
            docker compose down --remove-orphans
            docker compose up -d --build
